name: NetflixFrontend stack build-deploy

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}


          if [[ -z $DOCKERHUB_USERNAME ]] || [[ -z $DOCKERHUB_PASSWORD ]]; then
            echo DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets should be configured
            exit 1
          fi

          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          echo "login success"

          IMAGE_NAME=$DOCKERHUB_USERNAME/netflix-frontend:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          echo "New Docker build"
          docker push $IMAGE_NAME

      - name: Checkout infrastructure repo
        uses: actions/checkout@v3
        with:
          repository: https://github.com/ofekhalabi/NetflixInfra.git
          token: ${{ secrets.REPO_TOKEN }}  # The GITHUB_TOKEN secret is a GitHub access token.
          path: ./NetflixInfra

      - name: Update YAML manifests
        run: |
          cd ./NetflixInfra/k8s/NetflixFrontend
          DOCKERHUB_USERNAME= ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME=$DOCKERHUB_USERNAME/netflix-frontend:${{ github.run_number }}
          yq e ".spec.template.spec.containers.image = \"$IMAGE_NAME\"" -i deployment.yaml

      - name: Commit and Push changes
        run: |
           cd ./NetflixInfra
           git config --local user.email "github@action"
           git config --local user.name "auto-update"
           git add /k8s/NetflixFrontend/deployment.yaml
           git commit -m "Update image to $IMAGE_NAME"
           git push origin main